### ISSUE TITLE
Possibly hacked?

### ISSUE THREAD

**Issue by nikskiz** [emersion/phproxy-improved#11]
There is a possibility the proxy is hacked:

if you browse to index.php?q=uggc%3A%2F%2Fjjj.pnaoreenonxref.pbz.nh%2Fpngrtbel%3Fvq%3D25

**Comment by emersion** [comment]
Can you describe the problem please?

What happens?

**Comment by nikskiz** [comment]
Sorry for the vague comment.

Based off a previous installation on a different server I could see the following uri being hit by random IP's:
index.php?q=uggc%3A%2F%2Fjjj.pnaoreenonxref.pbz.nh%2Fpngrtbel%3Fvq%3D25

So I did a fresh installation and I could see that the uri is still there, which you can view via:
http://52.62.245.157/phproxy-improved/index.php

However, the fraudulent page is still showing up:
http://52.62.245.157/phproxy-improved/index.php?q=uggc%3A%2F%2Fjjj.pnaoreenonxref.pbz.nh%2Fpngrtbel%3Fvq%3D25

It seems to be referencing http://canberrabakers.com.au

**Comment by jeff142** [comment]
This is basically intended to be this way, they are directly linking to a proxifed page.
Just like how index.php?q=uggcf%3A%2F%2Fjjj.fgnegcntr.pbz%2F links to the start page.

Unless im missing something here, this looks like just direct links.

Jeff S
